/**
 * Backup data to be loaded in case WFS service unreachable
 */

export const data = {
    type: 'FeatureCollection',
    bbox: [
        379693.24,
        5807577.99,
        406060.38,
        5832713.22
    ],
    totalFeatures: 32,
    features: [
        {
            type: 'Feature',
            id: '172664',
            geometry: {
                type: 'Point',
                coordinates: [
                    393324.4,
                    5827585.72
                ]
            },
            properties: {
                ID: '172664',
                BETREIBER: 'Vattenfall Europe Wärme AG',
                STANDORT: 'Blankenburger Str. 129/141',
                PLZ: '13156',
                ANLAGENBEZ: 'HW Blankenburger Str.',
                SD2005: '12537',
                SD2006: '12502',
                SD2007: '11897',
                SD2008: '12867',
                SD2009: '13489',
                SD2010: '15078',
                SD2011: '14072',
                SD2012: '15384',
                SD2013: '13340',
                SD2014: '9268',
                SD2015: '9771',
                SD2016: '10571',
                SD2017: '9465',
                X: '393324',
                Y: '5827586',
                BIMSCHV: '1.2.3.1 V ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0607',
                AGGREGAT1: 'BHKW 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'BHKW 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Dampfkessel 1  ',
                STATUS3: 'außer Betrieb',
                AGGREGAT4: 'Dampfkessel 2',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Dampfkessel 3',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'Dampfkessel 4',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172621',
            geometry: {
                type: 'Point',
                coordinates: [
                    395004.77,
                    5817312.79
                ]
            },
            properties: {
                ID: '172621',
                BETREIBER: 'Vattenfall Europe Wärme AG',
                STANDORT: 'Eichenstr. 7',
                PLZ: '12435',
                ANLAGENBEZ: 'HW Treptow',
                SD2005: '',
                SD2006: '',
                SD2007: '',
                SD2008: '',
                SD2009: '',
                SD2010: '',
                SD2011: '',
                SD2012: '',
                SD2013: '',
                SD2014: '',
                SD2015: '',
                SD2016: '',
                SD2017: '',
                X: '395005',
                Y: '5817313',
                BIMSCHV: '1.2.3.1 V',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'im Bau',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: 'n.n.',
                AGGREGAT1: 'Heißwassererzeuger',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: '',
                STATUS2: '',
                AGGREGAT3: '',
                STATUS3: '',
                AGGREGAT4: '',
                STATUS4: '',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '166988',
            geometry: {
                type: 'Point',
                coordinates: [
                    389034.86,
                    5822337.94
                ]
            },
            properties: {
                ID: '166988',
                BETREIBER: 'Bayer AG',
                STANDORT: 'Müllerstr. 178',
                PLZ: '13353',
                ANLAGENBEZ: 'HKW Bayer',
                SD2005: '58882',
                SD2006: '59768',
                SD2007: '56103',
                SD2008: '50853',
                SD2009: '48303',
                SD2010: '45132',
                SD2011: '40203',
                SD2012: '40275',
                SD2013: '41281',
                SD2014: '42056',
                SD2015: '40901',
                SD2016: '40517',
                SD2017: '39245',
                X: '389035',
                Y: '5822338',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-1247',
                AGGREGAT1: 'Dampfkessel 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Dampfkessel 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Dampfkessel 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Dampfkessel 4',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172368',
            geometry: {
                type: 'Point',
                coordinates: [
                    399941.75,
                    5809546.95
                ]
            },
            properties: {
                ID: '172368',
                BETREIBER: 'Blockheizkraftwerks- Träger- und Betreibergesellschaft mbH Berlin',
                STANDORT: 'Albert-Einstein-Str. 22',
                PLZ: '12489',
                ANLAGENBEZ: 'HKW Adlershof',
                SD2005: '63325',
                SD2006: '39648',
                SD2007: '32995',
                SD2008: '28645',
                SD2009: '25889',
                SD2010: '30250',
                SD2011: '34757',
                SD2012: '38468',
                SD2013: '28905',
                SD2014: '21367',
                SD2015: '20501',
                SD2016: '37578',
                SD2017: '36450',
                X: '399942',
                Y: '5809547',
                BIMSCHV: '1.1 G/E ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0525',
                AGGREGAT1: 'Heißwassererzeuger 1 ',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 4',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Gasturbine 1',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'BHKW 1',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: 'BHKW 2',
                STATUS7: 'funktionsfähig',
                AGGREGAT8: 'BHKW 3',
                STATUS8: 'funktionsfähig',
                AGGREGAT9: 'BHKW 4',
                STATUS9: 'funktionsfähig',
                AGGREGAT10: 'Elektrokessel 1 (EDE)',
                STATUS10: 'funktionsfähig',
                AGGREGAT11: 'Elektrokessel 2 (PTH)',
                STATUS11: 'funktionsfähig',
                AGGREGAT12: 'Elektrokessel 3 (PTH)',
                STATUS12: 'funktionsfähig',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '181711',
            geometry: {
                type: 'Point',
                coordinates: [
                    395012.48,
                    5815404.81
                ]
            },
            properties: {
                ID: '181711',
                BETREIBER: 'Fernheizwerk Neukölln AG',
                STANDORT: 'Weigandufer 49',
                PLZ: '12059',
                ANLAGENBEZ: 'Fernheizwerk',
                SD2005: '74107',
                SD2006: '73541',
                SD2007: '75030',
                SD2008: '54520',
                SD2009: '64049',
                SD2010: '70217',
                SD2011: '44926',
                SD2012: '39810',
                SD2013: '42334',
                SD2014: '49576',
                SD2015: '55974',
                SD2016: '73177',
                SD2017: '74655',
                X: '395012',
                Y: '5815405',
                BIMSCHV: '1.1 G/E ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0467',
                AGGREGAT1: 'BHKW 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'BHKW 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'BHKW 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'BHKW 8',
                STATUS4: 'geplant',
                AGGREGAT5: 'BHKW 4',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'BHKW 5',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: 'BHKW 6',
                STATUS7: 'funktionsfähig',
                AGGREGAT8: 'BHKW 7',
                STATUS8: 'funktionsfähig',
                AGGREGAT9: 'Elektro- Heißwassererzeuger 1 ',
                STATUS9: 'funktionsfähig',
                AGGREGAT10: 'Elektro- Heißwassererzeuger 2',
                STATUS10: 'funktionsfähig',
                AGGREGAT11: 'Elektro- Heißwassererzeuger 3',
                STATUS11: 'funktionsfähig',
                AGGREGAT12: 'Elektro- Heißwassererzeuger 4',
                STATUS12: 'funktionsfähig',
                AGGREGAT13: 'Heißwassererzeuger 1',
                STATUS13: 'funktionsfähig',
                AGGREGAT14: 'Heißwassererzeuger 2',
                STATUS14: 'funktionsfähig',
                AGGREGAT15: 'Dampfkessel 3',
                STATUS15: 'funktionsfähig',
                AGGREGAT16: 'Heißwassererzeuger 4',
                STATUS16: 'funktionsfähig',
                AGGREGAT17: 'Dampfkessel 6',
                STATUS17: 'funktionsfähig',
                AGGREGAT18: 'Heißwassererzeuger 8',
                STATUS18: 'funktionsfähig',
                AGGREGAT19: 'Heißwassererzeuger 9',
                STATUS19: 'funktionsfähig'
            }
        },
        {
            type: 'Feature',
            id: '184913',
            geometry: {
                type: 'Point',
                coordinates: [
                    399123.56,
                    5809327.25
                ]
            },
            properties: {
                ID: '184913',
                BETREIBER: 'Innogy SE GmbH',
                STANDORT: 'Köpenicker Str. 32',
                PLZ: '12355',
                ANLAGENBEZ: 'HHKW Neukölln (Rudow)',
                SD2005: '44518',
                SD2006: '27954',
                SD2007: '7769',
                SD2008: '3383',
                SD2009: '4813',
                SD2010: '9561',
                SD2011: '3598',
                SD2012: '5245',
                SD2013: '3496',
                SD2014: '2584',
                SD2015: '1821',
                SD2016: '5055',
                SD2017: '6630',
                X: '399124',
                Y: '5809327',
                BIMSCHV: '1.1 G/E , 8.1.1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0655',
                AGGREGAT1: 'Dampfturbine 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Dampferzeuger 1',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Dampferzeuger 2',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 1',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Heißwassererzeuger 2',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'Heißwassererzeuger 3',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172680',
            geometry: {
                type: 'Point',
                coordinates: [
                    389685.78,
                    5821495.62
                ]
            },
            properties: {
                ID: '172680',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Scharnhorststr. 3a',
                PLZ: '10115',
                ANLAGENBEZ: 'Fernheizwerk Scharnhorststrasse',
                SD2005: '4682',
                SD2006: '7340',
                SD2007: '10083',
                SD2008: '14238',
                SD2009: '29196',
                SD2010: '45617',
                SD2011: '25681',
                SD2012: '35259',
                SD2013: '31088',
                SD2014: '23324',
                SD2015: '24997',
                SD2016: '28344',
                SD2017: '24765',
                X: '389686',
                Y: '5821496',
                BIMSCHV: '1.1 G/E ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0611',
                AGGREGAT1: 'HWE 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'HWE 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'HWE 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'HWE 4',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'DE 1',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'BHKW',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: 'Gasturbine mit Abhitzekessel',
                STATUS7: 'geplant',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172654',
            geometry: {
                type: 'Point',
                coordinates: [
                    392833.06,
                    5819105.94
                ]
            },
            properties: {
                ID: '172654',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Köpenicker Str. 60',
                PLZ: '10179',
                ANLAGENBEZ: 'HKW Mitte',
                SD2005: '794076',
                SD2006: '992539',
                SD2007: '967489',
                SD2008: '1033222',
                SD2009: '916755',
                SD2010: '1002887',
                SD2011: '1012243',
                SD2012: '890980',
                SD2013: '923866',
                SD2014: '795776',
                SD2015: '831156',
                SD2016: '872230',
                SD2017: '974109',
                X: '392833',
                Y: '5819106',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0638',
                AGGREGAT1: 'Gasturbine 1 mit Abhitzekessel und Dampfturbine 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Gasturbine 2 mit Abhitzekessel und Dampfturbine 1',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 1',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 2',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '169709',
            geometry: {
                type: 'Point',
                coordinates: [
                    397885.32,
                    5816620.07
                ]
            },
            properties: {
                ID: '169709',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Köpenicker Chaussee 42 - 45',
                PLZ: '10317',
                ANLAGENBEZ: 'HKW Klingenberg',
                SD2005: '1533756',
                SD2006: '1428235',
                SD2007: '1459527',
                SD2008: '1466991',
                SD2009: '1510902',
                SD2010: '1661363',
                SD2011: '1439473',
                SD2012: '1510203',
                SD2013: '1378892',
                SD2014: '1345693',
                SD2015: '1295610',
                SD2016: '1377759',
                SD2017: '944442',
                X: '397885',
                Y: '5816620',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0612',
                AGGREGAT1: 'Dampfkessel 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Dampfkessel 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Dampfkessel 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Dampfkessel 4',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '214979',
            geometry: {
                type: 'Point',
                coordinates: [
                    398337.9486,
                    5816234.5005
                ]
            },
            properties: {
                ID: '214979',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Köpenicker Chaussee 40 - 41',
                PLZ: '10317',
                ANLAGENBEZ: 'GuD-HKW Klingenberg',
                SD2005: '',
                SD2006: '',
                SD2007: '',
                SD2008: '',
                SD2009: '',
                SD2010: '',
                SD2011: '',
                SD2012: '',
                SD2013: '',
                SD2014: '',
                SD2015: '',
                SD2016: '',
                SD2017: '',
                X: '398338',
                Y: '5816235',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'geplant',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '',
                AGGREGAT1: '',
                STATUS1: '',
                AGGREGAT2: '',
                STATUS2: '',
                AGGREGAT3: '',
                STATUS3: '',
                AGGREGAT4: '',
                STATUS4: '',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '222276',
            geometry: {
                type: 'Point',
                coordinates: [
                    385444.11,
                    5820360.73
                ]
            },
            properties: {
                ID: '222276',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Am Spreebord 5',
                PLZ: '10589',
                ANLAGENBEZ: 'HKW Charlottenburg',
                SD2005: '120930',
                SD2006: '152923',
                SD2007: '77989',
                SD2008: '89841',
                SD2009: '112542',
                SD2010: '151729',
                SD2011: '99684',
                SD2012: '134638',
                SD2013: '96977',
                SD2014: '50207',
                SD2015: '36672',
                SD2016: '143146',
                SD2017: '103828',
                X: '385444',
                Y: '5820361',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0590',
                AGGREGAT1: 'Gasturbine 4 mit Abhitzekessel',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Gasturbine 5 mit Abhitzekessel',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Hilfsdampferzeuger 1',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Hilfsdampferzeuger 2',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Hilfsdampferzeuger 3',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '173097',
            geometry: {
                type: 'Point',
                coordinates: [
                    385073.55,
                    5809634.21
                ]
            },
            properties: {
                ID: '173097',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Ostpreußendamm 61',
                PLZ: '12207',
                ANLAGENBEZ: 'HKW Lichterfelde',
                SD2005: '733070',
                SD2006: '704524',
                SD2007: '630006',
                SD2008: '603970',
                SD2009: '474118',
                SD2010: '496548',
                SD2011: '457208',
                SD2012: '574757',
                SD2013: '443827',
                SD2014: '324723',
                SD2015: '378595',
                SD2016: '439498',
                SD2017: '364959',
                X: '385074',
                Y: '5809634',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-1063',
                AGGREGAT1: 'Block 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Block 3',
                STATUS2: 'außer Betrieb',
                AGGREGAT3: 'Hilfsdampferzeuger',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: '',
                STATUS4: '',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '234566',
            geometry: {
                type: 'Point',
                coordinates: [
                    385186.0,
                    5809794.0
                ]
            },
            properties: {
                ID: '234566',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Ostpreußendamm 61',
                PLZ: '12207',
                ANLAGENBEZ: 'GuD-HKW Lichterfelde',
                SD2005: '',
                SD2006: '',
                SD2007: '',
                SD2008: '',
                SD2009: '',
                SD2010: '',
                SD2011: '',
                SD2012: '',
                SD2013: '',
                SD2014: '',
                SD2015: '',
                SD2016: '',
                SD2017: '88666',
                X: '385186',
                Y: '5809794',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-1926',
                AGGREGAT1: 'Gas- und Dampfturbine',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 1',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 2',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 3',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Hilfsdampferzeuger 1',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '173303',
            geometry: {
                type: 'Point',
                coordinates: [
                    403576.9,
                    5810422.51
                ]
            },
            properties: {
                ID: '173303',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Wendenschloßstr. 180',
                PLZ: '12557',
                ANLAGENBEZ: 'BHKW Köpenick',
                SD2005: '23859',
                SD2006: '23496',
                SD2007: '19706',
                SD2008: '20473',
                SD2009: '20835',
                SD2010: '24656',
                SD2011: '19893',
                SD2012: '18688',
                SD2013: '16148',
                SD2014: '16295',
                SD2015: '19083',
                SD2016: '19642',
                SD2017: '21050',
                X: '403577',
                Y: '5810423',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0589',
                AGGREGAT1: 'BHKW 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Gasturbine 1 mit Abhitzekessel',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Gasturbine 2 mit Abhitzekessel',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 1',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Heißwassererzeuger 2',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'Heißwassererzeuger 3',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172656',
            geometry: {
                type: 'Point',
                coordinates: [
                    399853.84,
                    5820232.26
                ]
            },
            properties: {
                ID: '172656',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Rhinstr. 70',
                PLZ: '12681',
                ANLAGENBEZ: 'HKW Marzahn',
                SD2005: '80375',
                SD2006: '74031',
                SD2007: '28949',
                SD2008: '15804',
                SD2009: '47720',
                SD2010: '92397',
                SD2011: '52693',
                SD2012: '73283',
                SD2013: '123521',
                SD2014: '94738',
                SD2015: '115610',
                SD2016: '151901',
                SD2017: '134764',
                X: '399854',
                Y: '5820232',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0619',
                AGGREGAT1: 'Dampfkessel 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 4',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 5',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 6',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Heißwassererzeuger 7',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'Heißwassererzeuger 8',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: 'Heißwassererzeuger 9',
                STATUS7: 'funktionsfähig',
                AGGREGAT8: 'Gas- und Dampfturbine',
                STATUS8: 'geplant',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '156701',
            geometry: {
                type: 'Point',
                coordinates: [
                    399211.55,
                    5832713.22
                ]
            },
            properties: {
                ID: '156701',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Schwanebecker Chaussee 17',
                PLZ: '13125',
                ANLAGENBEZ: 'HKW Buch',
                SD2005: '37696',
                SD2006: '40218',
                SD2007: '36275',
                SD2008: '33535',
                SD2009: '35827',
                SD2010: '39417',
                SD2011: '31784',
                SD2012: '31143',
                SD2013: '32502',
                SD2014: '27451',
                SD2015: '35622',
                SD2016: '41353',
                SD2017: '36514',
                X: '399212',
                Y: '5832713',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0609',
                AGGREGAT1: 'Gasturbine 1 mit Abhitzekessel ',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Dampfturbine',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Dampferzeuger 1',
                STATUS3: 'außer Betrieb',
                AGGREGAT4: 'Dampferzeuger 2',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Dampferzeuger 3',
                STATUS5: 'außer Betrieb',
                AGGREGAT6: 'Dampferzeuger 4',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: 'Dampferzeuger 5',
                STATUS7: 'funktionsfähig',
                AGGREGAT8: 'Heißwassererzeuger 1',
                STATUS8: 'funktionsfähig',
                AGGREGAT9: 'Heißwassererzeuger 2',
                STATUS9: 'funktionsfähig',
                AGGREGAT10: 'Heißwassererzeuger 3',
                STATUS10: 'funktionsfähig',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '173145',
            geometry: {
                type: 'Point',
                coordinates: [
                    387839.86,
                    5822070.7
                ]
            },
            properties: {
                ID: '173145',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Friedrich-Krause-Ufer 10 - 13',
                PLZ: '13353',
                ANLAGENBEZ: 'HKW Moabit',
                SD2005: '622940',
                SD2006: '379469',
                SD2007: '504558',
                SD2008: '546862',
                SD2009: '413406',
                SD2010: '615769',
                SD2011: '512118',
                SD2012: '393809',
                SD2013: '440865',
                SD2014: '480837',
                SD2015: '292414',
                SD2016: '504094',
                SD2017: '508992',
                X: '387840',
                Y: '5822071',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0618',
                AGGREGAT1: 'Block A',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Gasturbine 5',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Gasturbine 6',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Gasturbine 7',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Heizreservekessel 1',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'Heizreservekessel 2',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: 'Heizreservekessel 3',
                STATUS7: 'funktionsfähig',
                AGGREGAT8: 'Heißwassererzeuger 1',
                STATUS8: 'funktionsfähig',
                AGGREGAT9: 'Heißwassererzeuger 2',
                STATUS9: 'funktionsfähig',
                AGGREGAT10: 'Hilfsdampferzeuger',
                STATUS10: 'funktionsfähig',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172927',
            geometry: {
                type: 'Point',
                coordinates: [
                    387517.45,
                    5829296.3
                ]
            },
            properties: {
                ID: '172927',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Wallenroder Str. 2',
                PLZ: '13435',
                ANLAGENBEZ: 'Biomassenheizkraftwerk',
                SD2005: '104602',
                SD2006: '99286',
                SD2007: '88783',
                SD2008: '96712',
                SD2009: '92401',
                SD2010: '94844',
                SD2011: '68461',
                SD2012: '61502',
                SD2013: '58304',
                SD2014: '34616',
                SD2015: '29874',
                SD2016: '31465',
                SD2017: '36967',
                X: '387517',
                Y: '5829296',
                BIMSCHV: '1.1 G/E ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0276',
                AGGREGAT1: 'Dampfkessel (Biomasse)',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 1',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 2',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: '',
                STATUS4: '',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172916',
            geometry: {
                type: 'Point',
                coordinates: [
                    386193.45,
                    5828766.56
                ]
            },
            properties: {
                ID: '172916',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Lange Enden 15 - 25',
                PLZ: '13437',
                ANLAGENBEZ: 'Spitzenheizwerk',
                SD2005: '15890',
                SD2006: '16771',
                SD2007: '19724',
                SD2008: '13798',
                SD2009: '18862',
                SD2010: '27301',
                SD2011: '35059',
                SD2012: '42386',
                SD2013: '43153',
                SD2014: '37240',
                SD2015: '34447',
                SD2016: '37259',
                SD2017: '23555',
                X: '386193',
                Y: '5828767',
                BIMSCHV: '1.1 G/E ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0213',
                AGGREGAT1: 'Heißwassererzeuger 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Abhitzekessel 1',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'BHKW 1',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'Abhitzekessel 2',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: 'BHKW 2',
                STATUS7: 'funktionsfähig',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '166928',
            geometry: {
                type: 'Point',
                coordinates: [
                    380778.47,
                    5821975.09
                ]
            },
            properties: {
                ID: '166928',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Großer Spreering 5',
                PLZ: '13599',
                ANLAGENBEZ: 'HKW Reuter West',
                SD2005: '3099767',
                SD2006: '3068331',
                SD2007: '2936979',
                SD2008: '2955992',
                SD2009: '2658065',
                SD2010: '3227384',
                SD2011: '2587358',
                SD2012: '2555705',
                SD2013: '2992885',
                SD2014: '3036494',
                SD2015: '2976143',
                SD2016: '2531294',
                SD2017: '2491619',
                X: '380778',
                Y: '5821975',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0622',
                AGGREGAT1: 'Block D',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Block E',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Hilfskessel D',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Hilfskessel E',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Elektrodenkessel 1',
                STATUS5: 'im Bau',
                AGGREGAT6: 'Elektrodenkessel 2',
                STATUS6: 'im Bau',
                AGGREGAT7: 'Elektrodenkessel 3',
                STATUS7: 'im Bau',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '166927',
            geometry: {
                type: 'Point',
                coordinates: [
                    381063.31,
                    5821704.69
                ]
            },
            properties: {
                ID: '166927',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Otternbuchtstr. 11',
                PLZ: '13599',
                ANLAGENBEZ: 'HKW Reuter',
                SD2005: '603197',
                SD2006: '666947',
                SD2007: '578996',
                SD2008: '500403',
                SD2009: '448949',
                SD2010: '297683',
                SD2011: '505772',
                SD2012: '598072',
                SD2013: '602783',
                SD2014: '532607',
                SD2015: '471540',
                SD2016: '414886',
                SD2017: '450537',
                X: '381063',
                Y: '5821705',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0624',
                AGGREGAT1: 'Block C',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 1 ',
                STATUS2: 'geplant',
                AGGREGAT3: 'Heißwassererzeuger 2',
                STATUS3: 'geplant',
                AGGREGAT4: 'Heißwassererzeuger 3',
                STATUS4: 'geplant',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '132279',
            geometry: {
                type: 'Point',
                coordinates: [
                    385093.67,
                    5815953.39
                ]
            },
            properties: {
                ID: '132279',
                BETREIBER: 'Vattenfall Wärme Berlin AG',
                STANDORT: 'Forckenbeckstr. 3 - 6',
                PLZ: '14199',
                ANLAGENBEZ: 'HKW Wilmersdorf',
                SD2005: '11625',
                SD2006: '6659',
                SD2007: '6500',
                SD2008: '5395',
                SD2009: '14916',
                SD2010: '15845',
                SD2011: '3452',
                SD2012: '48490',
                SD2013: '18411',
                SD2014: '3447',
                SD2015: '1989',
                SD2016: '5876',
                SD2017: '14474',
                X: '385094',
                Y: '5815953',
                BIMSCHV: '1.1 G/E',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0625',
                AGGREGAT1: 'Gasturbine 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Gasturbine 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Gasturbine 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 1',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Heißwassererzeuger 2',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'Heißwassererzeuger 3',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '22365',
            geometry: {
                type: 'Point',
                coordinates: [
                    379693.24,
                    5822445.7
                ]
            },
            properties: {
                ID: '22365',
                BETREIBER: 'Bayerische Motoren Werke AG',
                STANDORT: 'Am Juliusturm 14 - 38',
                PLZ: '13599',
                ANLAGENBEZ: '',
                SD2005: '7714',
                SD2006: '7140',
                SD2007: '6246',
                SD2008: '5555',
                SD2009: '6281',
                SD2010: '7835',
                SD2011: '6807',
                SD2012: '6816',
                SD2013: '6612',
                SD2014: '5745',
                SD2015: '6157',
                SD2016: '7939',
                SD2017: '8604',
                X: '379693',
                Y: '5822446',
                BIMSCHV: '1.2.3.1 V',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-1320',
                AGGREGAT1: 'Heißwassererzeuger 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 4',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'BHKW',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172915',
            geometry: {
                type: 'Point',
                coordinates: [
                    384259.94,
                    5823638.73
                ]
            },
            properties: {
                ID: '172915',
                BETREIBER: 'Berliner Flughafen GmbH',
                STANDORT: 'Kurt-Schumacher-Damm 220-224',
                PLZ: '13405',
                ANLAGENBEZ: '',
                SD2005: '8332',
                SD2006: '8551',
                SD2007: '8090',
                SD2008: '8309',
                SD2009: '8716',
                SD2010: '10388',
                SD2011: '8550',
                SD2012: '9319',
                SD2013: '9379',
                SD2014: '8060',
                SD2015: '8975',
                SD2016: '9233',
                SD2017: '8870',
                X: '384260',
                Y: '5823639',
                BIMSCHV: '1.2.3.1 V ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0664',
                AGGREGAT1: 'Heißwassererzeuger 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: '',
                STATUS4: '',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '173797',
            geometry: {
                type: 'Point',
                coordinates: [
                    394860.0,
                    5813432.89
                ]
            },
            properties: {
                ID: '173797',
                BETREIBER: 'Blockheizkraftwerks- Träger- und Betreibergesellschaft mbH Berlin KWK (auf dem Gelände NK Spezialpapier NK GmbH)',
                STANDORT: 'Woermannkehre 2',
                PLZ: '12359',
                ANLAGENBEZ: 'ehem. Melitta',
                SD2005: '21216',
                SD2006: '21106',
                SD2007: '17918',
                SD2008: '20830',
                SD2009: '17128',
                SD2010: '18400',
                SD2011: '17164',
                SD2012: '13016',
                SD2013: '97',
                SD2014: '126',
                SD2015: '269',
                SD2016: '303',
                SD2017: '388',
                X: '394860',
                Y: '5813433',
                BIMSCHV: '1.2.3.2 V ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14280-0156',
                AGGREGAT1: 'Dampfkessel 1  ',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Gasturbine mit Abhitzekessel',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: '',
                STATUS3: '',
                AGGREGAT4: '',
                STATUS4: '',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172484',
            geometry: {
                type: 'Point',
                coordinates: [
                    398463.45,
                    5813369.39
                ]
            },
            properties: {
                ID: '172484',
                BETREIBER: 'Blockheizkraftwerks- Träger- und Betreibergesellschaft mbH Berlin',
                STANDORT: 'Schnellerstr. 138',
                PLZ: '12439',
                ANLAGENBEZ: 'HKW Schöneweide',
                SD2005: '46684',
                SD2006: '79792',
                SD2007: '59658',
                SD2008: '63821',
                SD2009: '73871',
                SD2010: '78967',
                SD2011: '59706',
                SD2012: '70150',
                SD2013: '74934',
                SD2014: '65630',
                SD2015: '73955',
                SD2016: '77545',
                SD2017: '76155',
                X: '398463',
                Y: '5813369',
                BIMSCHV: '1.2.1 V',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0427',
                AGGREGAT1: 'Dampfkessel 2',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Dampfkessel 3',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: '',
                STATUS3: '',
                AGGREGAT4: '',
                STATUS4: '',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '4298',
            geometry: {
                type: 'Point',
                coordinates: [
                    389812.05,
                    5809204.2
                ]
            },
            properties: {
                ID: '4298',
                BETREIBER: 'Daimler Chrysler AG',
                STANDORT: 'Daimlerstr. 143',
                PLZ: '12277',
                ANLAGENBEZ: 'Heizwerk Süd',
                SD2005: '15692',
                SD2006: '14208',
                SD2007: '11669',
                SD2008: '11269',
                SD2009: '10871',
                SD2010: '13690',
                SD2011: '12297',
                SD2012: '11530',
                SD2013: '10687',
                SD2014: '9351',
                SD2015: '9217',
                SD2016: '9482',
                SD2017: '6878',
                X: '389812',
                Y: '5809204',
                BIMSCHV: '1.2.3.1 V \n',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0137',
                AGGREGAT1: 'Heißwassererzeuger 1 S',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 2 S',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 3 S',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 4 S',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Heißwassererzeuger 5 S',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '173083',
            geometry: {
                type: 'Point',
                coordinates: [
                    392734.73,
                    5812878.29
                ]
            },
            properties: {
                ID: '173083',
                BETREIBER: 'DEK Deutsche Extrakt Kaffee GmbH',
                STANDORT: 'Cafeastr. 1',
                PLZ: '12347',
                ANLAGENBEZ: '',
                SD2005: '16896',
                SD2006: '18150',
                SD2007: '16732',
                SD2008: '16555',
                SD2009: '16498',
                SD2010: '17623',
                SD2011: '15898',
                SD2012: '16744',
                SD2013: '18918',
                SD2014: '24085',
                SD2015: '28631',
                SD2016: '23153',
                SD2017: '19970',
                X: '392735',
                Y: '5812878',
                BIMSCHV: '1.2.3.1 V ,  1.2.4 V',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0627',
                AGGREGAT1: 'Gasturbine mit Abhitzekessel',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Dampfkessel 1',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Dampfkessel 2',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Dampfkessel 3',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Dampfkessel 4',
                STATUS5: 'außer Betrieb',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '15686',
            geometry: {
                type: 'Point',
                coordinates: [
                    384437.78,
                    5816955.79
                ]
            },
            properties: {
                ID: '15686',
                BETREIBER: 'Deutsche Rentenversicherung Bund',
                STANDORT: 'Seesener Str. 62 - 64',
                PLZ: '10709',
                ANLAGENBEZ: '',
                SD2005: '13816',
                SD2006: '13902',
                SD2007: '12251',
                SD2008: '13220',
                SD2009: '11557',
                SD2010: '13350',
                SD2011: '11186',
                SD2012: '9903',
                SD2013: '9824',
                SD2014: '8714',
                SD2015: '8830',
                SD2016: '7782',
                SD2017: '11231',
                X: '384438',
                Y: '5816956',
                BIMSCHV: '1.2.3.1 V ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0852',
                AGGREGAT1: 'Heißwassererzeuger 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Heißwassererzeuger 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Heißwassererzeuger 3',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'BHKW 2',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'BHKW 3',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'BHKW 4',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '8882',
            geometry: {
                type: 'Point',
                coordinates: [
                    382908.15,
                    5818284.8
                ]
            },
            properties: {
                ID: '8882',
                BETREIBER: 'Messe Berlin GmbH',
                STANDORT: 'Messedamm 22',
                PLZ: '14055',
                ANLAGENBEZ: '',
                SD2005: '13267',
                SD2006: '10566',
                SD2007: '12486',
                SD2008: '12817',
                SD2009: '12901',
                SD2010: '12658',
                SD2011: '11636',
                SD2012: '12670',
                SD2013: '10857',
                SD2014: '9880',
                SD2015: '8830',
                SD2016: '10624',
                SD2017: '12235',
                X: '382908',
                Y: '5818285',
                BIMSCHV: ' 1.2.3.1 V , 1.2.1 V',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0592',
                AGGREGAT1: 'BHKW 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'BHKW 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Dampfkessel (Pellet)',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: 'Heißwassererzeuger 1',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'Heißwassererzeuger 5',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: 'Heißwassererzeuger 6',
                STATUS6: 'funktionsfähig',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '172517',
            geometry: {
                type: 'Point',
                coordinates: [
                    400673.17,
                    5807577.99
                ]
            },
            properties: {
                ID: '172517',
                BETREIBER: 'Vattenfall Europe Wärme AG',
                STANDORT: 'Nelkenweg 100',
                PLZ: '12524',
                ANLAGENBEZ: 'HW Altglienicke',
                SD2005: '12244',
                SD2006: '8871',
                SD2007: '7910',
                SD2008: '7572',
                SD2009: '7916',
                SD2010: '7912',
                SD2011: '7242',
                SD2012: '8481',
                SD2013: '7329',
                SD2014: '4355',
                SD2015: '4611',
                SD2016: '5340',
                SD2017: '5684',
                X: '400673',
                Y: '5807578',
                BIMSCHV: '1.2.3.1 V ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0605',
                AGGREGAT1: 'Dampfkessel 3 ',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Dampfkessel 4',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'Dampfkessel 5',
                STATUS3: 'außer Betrieb',
                AGGREGAT4: 'Dampfkessel 6',
                STATUS4: 'funktionsfähig',
                AGGREGAT5: 'BHKW ',
                STATUS5: 'funktionsfähig',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        },
        {
            type: 'Feature',
            id: '173938',
            geometry: {
                type: 'Point',
                coordinates: [
                    406060.38,
                    5812725.04
                ]
            },
            properties: {
                ID: '173938',
                BETREIBER: 'Vattenfall Europe Wärme AG',
                STANDORT: 'Stillerzeile 10 - 12',
                PLZ: '12587',
                ANLAGENBEZ: 'HW Friedrichshagen',
                SD2005: '8928',
                SD2006: '9686',
                SD2007: '9128',
                SD2008: '9479',
                SD2009: '9620',
                SD2010: '10461',
                SD2011: '9100',
                SD2012: '9386',
                SD2013: '9816',
                SD2014: '7575',
                SD2015: '7657',
                SD2016: '8272',
                SD2017: '8209',
                X: '406060',
                Y: '5812725',
                BIMSCHV: '1.2.3.1 V ',
                NACE_WZ2008: '35.30',
                NACE_WZ2008_BEZ: 'Wärme- und Kälteversorgung',
                STATUS_TYP: 'funktionsfähig',
                ANLAGENART: 'Feuerungsanlage',
                DEHST_AZ: '14310-0608',
                AGGREGAT1: 'Dampfkessel 1',
                STATUS1: 'funktionsfähig',
                AGGREGAT2: 'Dampfkessel 2',
                STATUS2: 'funktionsfähig',
                AGGREGAT3: 'BHKW 1',
                STATUS3: 'funktionsfähig',
                AGGREGAT4: '',
                STATUS4: '',
                AGGREGAT5: '',
                STATUS5: '',
                AGGREGAT6: '',
                STATUS6: '',
                AGGREGAT7: '',
                STATUS7: '',
                AGGREGAT8: '',
                STATUS8: '',
                AGGREGAT9: '',
                STATUS9: '',
                AGGREGAT10: '',
                STATUS10: '',
                AGGREGAT11: '',
                STATUS11: '',
                AGGREGAT12: '',
                STATUS12: '',
                AGGREGAT13: '',
                STATUS13: '',
                AGGREGAT14: '',
                STATUS14: '',
                AGGREGAT15: '',
                STATUS15: '',
                AGGREGAT16: '',
                STATUS16: '',
                AGGREGAT17: '',
                STATUS17: '',
                AGGREGAT18: '',
                STATUS18: '',
                AGGREGAT19: '',
                STATUS19: ''
            }
        }
    ],
    crs: {
        type: 'name',
        properties: {
            name: 'EPSG:25833'
        }
    }
};
